### ISSUE TITLE
Generated packer templates doesn't work with packer 1.3.5

### ISSUE THREAD

**Issue by 616b2f** [SubPointSolutions/uplift-packer#9]
Hi,

I found this repo and it looks really promising. Thank you for making this open source! But as I tried to use it I found that you depend on some tools like packer (I want't familiar with them before) and it was not clear for me which tools you depend on from README file.

What I would suggest, adding Prerequisite section in your README file, which lists the tools and version which you use to build this vagrant boxes.

And maybe adding a License file :)

What do you thinks?

**Comment by SubPointSupport** [comment]
Hi @616b2f, thanks for raising this. All valid concerns, agreed.

First of all, what is the scenario you are trying to implement, and what are the packer errors you see?

We open sourced this project a few weeks ago and still catching up on documentation and blog posts. 

Prerequisites sounds like a good idea. Both README and potentially PS6 script to validate and install needed dependencies might be a quick win. We'll check the license but overall, use it as you see the fit.

Next, quick start is possible with already pre-baked Vagrant Boxes. Check them out too:
> https://app.vagrantup.com/SubPointSolutions

We also put a few examples how these boxes can be used for complex setup:
> https://github.com/SubPointSolutions/uplift-contrib/tree/master/uplift-vagrant

**Comment by 616b2f** [comment]
> First of all, what is the scenario you are trying to implement, and what are the packer errors you see?

thank you for quick response. I just want to start a VM with only sharepoint preinstalled to test WS-Federation module for IdentityServer4 that I am currently porting to netstandard2.0. I will add it as IDP and look if it runs smoothly.

when i run the build script I got invalid template here:

```
PS C:\abc\uplift-packer\packer\win-2016-datacenter-sp2016rtm> packer validate .\packer-template.generated.json
Template validation failed. Errors are shown below.

Errors validating build 'vagrant'. 3 error(s) occurred:

* unknown configuration key: "box_file"
* unknown configuration key: "box_provider"
* unknown configuration key: "builder"
```

to get it valid I had to change this:

```
index dae2845..092fe96 100644
--- a/packer/packer_templates/common/builders-win-2016-vagrant.json
+++ b/packer/packer_templates/common/builders-win-2016-vagrant.json
@@ -1,13 +1,7 @@
 {
     "builders": [
-     {
-        "type": "vagrant",
-
-        "box_provider": "virtualbox",
-        "box_file": ".ovf",
-        "box_name": "{{user `uplf_input_box_name` }}",
-
-        "builder": {
+        {
+            "source_path": "{{user `uplf_input_box_name` }}",
             "type": "virtualbox-ovf",

             "output_directory": "{{user `uplf_output_directory`}}",
@@ -31,7 +25,6 @@
             "winrm_password": "vagrant",
             "winrm_timeout": "12h"
         }
-    }
     ],
     "provisioners": [

```

I am not sure if it works correct, but the `packer validate` shows no errors. I will test it when the download of resources is ready :).

> Prerequisites sounds like a good idea. Both README and potentially PS6 script to validate and install needed dependencies might be a quick win.

Sound good to me.

> We'll check the license but overall, use it as you see the fit.

Sound's like MIT for me, this would be awesome :).

> Next, quick start is possible with already pre-baked Vagrant Boxes. Check them out too:
> 
> https://app.vagrantup.com/SubPointSolutions

Thank you, I will try them out. Is there any box only with things that Sharepoint needs to run. Because any of them that contains Sharepoint has also VisualStudio in it or did i miss something?

When I got a working box I will make a PR with changes I made, so you can validate it and decide if its fits.

**Comment by SubPointSupport** [comment]
Right, in this case it might be better to park it until we write more guides on how to use all this tech. Just conscious on the learning curve and all complexity underneath.

In nutshell, the project consists of three parts:
1)  PS6 module to download and serve binaries (ISO, installs, pactches and so on)
2) Packer is used to produce VM images, which then used by Vagrant.
3) Vagrant Cloud contains ready to use images.

We leverage Hashicorp tooling (packer/vagrant) aiming to simplify windows/sharepoint workloads. 

Btw, just blogged about the downloading automation here, and general overview will come today:
> https://medium.com/@SubPointSocial/easy-installation-media-download-for-busy-sharepoint-engineers-5bd97d26f302

Now, depending on the image, packer builds might be quite complex. Average time is around 60-90 minutes or more. That involves patching, installs, some tests and optimizations - really-really heavy things. Output is an image which can be used by Vagrant.

Vagrant uses images to spin up virtual machines. We went with VirtualBox because it works well on both windows/macos laptops.

At this stage, with Vagrant, we finally can start building VMs. Most common case is [multi-machine](https://www.vagrantup.com/docs/multi-machine/) environment which consist of domain controller and other vm (sql, sharepoint, dev-test, etc).

Vagrant configuration defines two vms, and additional provision kicks-in:
* create domain controller (dc promo and stuff)
* join other VM into dc
* finish SQL server image
* finish SharePoint installs

We don't ship snapshots of existing SharePoint/SQL but rather pre-installed images with sysprep which then need completion. It won't give SharePoint farm straight away but will get you one after 40-60 minutes depending on the hardware.

So yea, we'll write several posts on how it works, on Packer/Vagrant why's, and cover the most comoon scenarios such as dc, dc + sql, dc + sql + sharepoint + vs2017 this/next week.

As for your builds, we don't use native packer builds. While generated templates are correct packer templates, we use builds via `Invoke-Build` automation, documented here:

> https://github.com/SubPointSolutions/uplift-packer#building-packer-templates
```
# build minimal ubuntu-trusty64 box to validate all installs
invoke-build 
invoke-build -packerImageName ubuntu-trusty64

# forcing packer rebuild even if box exists
invoke-build -packerImageName ubuntu-trusty64 -Task PackerRebuild

# build windows base boxes
invoke-build -packerImageName win-2016-datacenter-soe  
```

Behind the scenes, this automation installs `packer-builder-vagrant` by @themalkolm. This is why you saw these errors, the building isn't found.  `invoke-build` also runs `packer validate` and other stuff for us, creates a separate folder for the build process and has more features. That's probably more advances scenarios for custom images.

Nevertheless, it looks like we better wait until docs come. Completely understand that getting into unfamiliar tool set might be challenging and frustrating without proper guides. As a teporary measure, probably vagrant cloud boxes with `uplift-contrib` examples might help:
> https://github.com/SubPointSolutions/uplift-contrib/tree/master/uplift-vagrant

**Comment by 616b2f** [comment]
I will try your ready to use images and wait for more docs. Thank you for clerification and keep up the good work!

**Comment by 616b2f** [comment]
I tried it with ready to use box "SubPointSolutions/win-2016-datacenter-sp2016latest-sql16-vs17" version "1902.18" and got following:

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'SubPointSolutions/win-2016-datacenter-sp2016latest-sql16-vs17' version '1902.18' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 3389 (guest) => 3389 (host) (adapter 1)
    default: 5985 (guest) => 55985 (host) (adapter 1)
    default: 5986 (guest) => 55986 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: WinRM address: 127.0.0.1:55985
    default: WinRM username: vagrant
    default: WinRM execution_time_limit: PT2H
    default: WinRM transport: plaintext
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```
in vbox I see it running but have a black screen and it hangs if I try to stop it or connect to it.

Any ideas?

**Comment by SubPointSupport** [comment]
No worries, @616b2f .

Here are two posts which explain Uplift in depth. Give it a go, let us know if it help. 
* [Open-sourcing The Uplift project — a Packer/Vagrant toolkit for SharePoint professionals](https://medium.com/@SubPointSocial/open-sourcing-the-uplift-project-a-packer-vagrant-toolkit-for-sharepoint-professionals-68ed3636d401)
* [Building a disposable Windows 2016 domain controller in 20 minutes with Vagrant](https://medium.com/@SubPointSocial/building-a-disposable-windows-2016-domain-controller-in-20-minutes-with-vagrant-fce6eb4e01bd)

We'll get a few more about domain joins, SQL Server and SharePoint early next week. Hope that helps with the direction for the time being.

**Comment by SubPointSupport** [comment]
Hey @616b2f , how did it go?

Three more posts on domain join, SQL and SharePoint server setup is due to early next week. 
Hope the current posts provide more visibility and understanding on how it all fits together.

**Comment by 616b2f** [comment]
@SubPointSupport Yes it worked, this posts make many things clearer to me, thank you. I have two things I wanna mention here:

- I had to install `vagrant-reload` plugin (this is missing in your posts or did I missed here something?)
- VMs freezes with black screen from the beginning (I activated VT-x in BIOS and deinstalled Hyper-V then it worked)

The second point doesn't have any thing todo with your images, just mentioned it if someone else have the same issues here. Also I am not sure if VT-x is really necessary, I activated it first and didn't try to deactivate it after that.

**Comment by SubPointSupport** [comment]
Good points!

That's right, recent Vagrant releases come with built-in reload functionality. We might want to migrate and test it, but for the time being we use  `vagrant-reload` plugin.

Hyper-V support has to be disabled. That comes due to VirtualBox usage. Worth mentioning but most of the time people "know" this. 

A few questions  - would you be interested in Hyper-V/VMWare support? 

Our quick research suggests that Hyper-V and VMware seem to be the primary choice for Windows/SharePoint professionals. We use VirtualBox to bring MacOS user on the same page, plus Vagrant supports better automation for VirtualBox. Depends on the feedback, we might get one of these virtualization platforms supported.

Another one - would you be interested in  Exchange automation? We had a few folks asking if we could put together a ready to use Vagrant workflow for Exchange 2016 deployment. Keen to hear more on what are the other routines we might help with.

Hope it all finally makes sense. Feel free to comment more or just close this ticket.

**Comment by 616b2f** [comment]
> Hyper-V support has to be disabled. That comes due to VirtualBox usage. Worth mentioning but most of the time people "know" this.

Agree, I knew that using both is not possible, but I forgot that I was using hyper-v (primarily use it because of LCOW in Docker for Windows).

I am not a Sharepoint professional but, I can share my opinion here :).

Hyper-V would be nice for windows, so you don't have to switch to VBox and back when you use Docker for Windows and LCOW in the same time. On my Mac I use also VBox so no need here for VMware from my site.

I don't use Exchange so also no interest for hat on my site.

Close the ticket, you provided more than enough information to get started :)

Thank you again for the great work and for sharing your work!

**Comment by andreasblueher** [comment]
@SubPointSupport we're using Hyper-V only as a Microsoft Gold Partner this is less a choice than a given. Still reading through the links and blogs you provided, but I have a question already. What are you using to finish SharePoint configuration? Currently we're using SPAutoInstaller but always outside of automated scenarios.

**Comment by SubPointSupport** [comment]
Hi @andreasblueher , 

Indeed, Hyper-V and VMWare seem to be the first choice across Microsoft professionals. We surely cannot ignore that fact and going to look into Hyper-V around mid-April. If it can be automated and scaled without manual work - we'll be fine, will see.

Initial posts were covering overview and simple domain controller setup. That should be alright to get feeling of how all this works. A few more posts on domain joins, SQL and SharePoint are to come.

Images which we release in Vagrant Cloud come in several flavour but in a context of SharePoint one can do all the job:
* sharepoint binaries + sql + vs17

It comes with sysprep and pre-installed SharePoint binaries, SQL server image and VS17 install. All work is implemented in PowerShell and PowerShell DSC (say, SharePointDSC module and some others). Intentionally use plain PowerShell and DSC (no puppet/chef/ansible) to support broader community, lower down solution complexity and entry learning curve.

Once this image is used, two VMs can be created:
* dc (simple Active Directory creation with PowerShell / DSC)
* sharepoint 

SharePoint VMs gets slightly tricky, the flow is implemented in PowerShell and DSC (SharePointDSC)
* join VM to domain
* complete SQL image 
* tweak broken IIS after sysprep, reboot VM
* setup bare minimum SP account in AD for SharePoint
* setup bare minimum SQL account in AD for SharePoint
* provision SP single farm
* provision minimum set of services
* optimize, ensure all services are up
* provision web app

It's a pretty standard setup flow, with some weird steps like fixing up IIS.

All of these steps can be ignored, say we need only farm and the rest will be done by you with your own PowerShell/DSC/their scripts, that's the thinking. Alternatively, you can also run all of them and get the minimal farm with web app ready.

Internally, for Packer/Vagrant, all comes to PowerShell or PowerShell DSC. Solution is split into several repositories to (1) prepare images with packer (2) deal with Vms and vagrant (3) show case examples.

**packer images**
latest sp image
> https://github.com/SubPointSolutions/uplift-packer/blob/master/packer/win-2016-datacenter-sp2016latest-sql16-vs17/packer-template.generated.json
* corresponding scripts:
> https://github.com/SubPointSolutions/uplift-packer/tree/master/packer/scripts/uplift.packer


**vagrant plugin and DSC/script for VM configurations**
https://github.com/SubPointSolutions/uplift-packer
> https://github.com/SubPointSolutions/uplift-vagrant/tree/master/vagrant-uplift/lib/scripts/vagrant

**uplift-contrib, a set of vagrantfiles, like a showcase**
checkout corresponding folders on particular setups
> https://github.com/SubPointSolutions/uplift-contrib/tree/master/uplift-vagrant
